/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUrlIdRouteImport } from './routes/u/$urlId'
import { Route as ESlugRouteImport } from './routes/e/$slug'
import { Route as ProtectedMeRouteImport } from './routes/_protected/me'
import { Route as ProtectedEventsIndexRouteImport } from './routes/_protected/events/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedProfileWizardRouteImport } from './routes/_protected/profile/wizard'
import { Route as ProtectedProfileEditRouteImport } from './routes/_protected/profile/edit'
import { Route as ProtectedEventsNewRouteImport } from './routes/_protected/events/new'
import { Route as UUrlIdPTokenRouteImport } from './routes/u/$urlId.p.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUrlIdRoute = UUrlIdRouteImport.update({
  id: '/u/$urlId',
  path: '/u/$urlId',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMeRoute = ProtectedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventsIndexRoute = ProtectedEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileWizardRoute = ProtectedProfileWizardRouteImport.update({
  id: '/profile/wizard',
  path: '/profile/wizard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileEditRoute = ProtectedProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventsNewRoute = ProtectedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const UUrlIdPTokenRoute = UUrlIdPTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => UUrlIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof ProtectedMeRoute
  '/e/$slug': typeof ESlugRoute
  '/u/$urlId': typeof UUrlIdRouteWithChildren
  '/events/new': typeof ProtectedEventsNewRoute
  '/profile/edit': typeof ProtectedProfileEditRoute
  '/profile/wizard': typeof ProtectedProfileWizardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/': typeof ProtectedEventsIndexRoute
  '/u/$urlId/p/$token': typeof UUrlIdPTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof ProtectedMeRoute
  '/e/$slug': typeof ESlugRoute
  '/u/$urlId': typeof UUrlIdRouteWithChildren
  '/events/new': typeof ProtectedEventsNewRoute
  '/profile/edit': typeof ProtectedProfileEditRoute
  '/profile/wizard': typeof ProtectedProfileWizardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events': typeof ProtectedEventsIndexRoute
  '/u/$urlId/p/$token': typeof UUrlIdPTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/me': typeof ProtectedMeRoute
  '/e/$slug': typeof ESlugRoute
  '/u/$urlId': typeof UUrlIdRouteWithChildren
  '/_protected/events/new': typeof ProtectedEventsNewRoute
  '/_protected/profile/edit': typeof ProtectedProfileEditRoute
  '/_protected/profile/wizard': typeof ProtectedProfileWizardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/events/': typeof ProtectedEventsIndexRoute
  '/u/$urlId/p/$token': typeof UUrlIdPTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/e/$slug'
    | '/u/$urlId'
    | '/events/new'
    | '/profile/edit'
    | '/profile/wizard'
    | '/api/auth/$'
    | '/events/'
    | '/u/$urlId/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/e/$slug'
    | '/u/$urlId'
    | '/events/new'
    | '/profile/edit'
    | '/profile/wizard'
    | '/api/auth/$'
    | '/events'
    | '/u/$urlId/p/$token'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/me'
    | '/e/$slug'
    | '/u/$urlId'
    | '/_protected/events/new'
    | '/_protected/profile/edit'
    | '/_protected/profile/wizard'
    | '/api/auth/$'
    | '/_protected/events/'
    | '/u/$urlId/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ESlugRoute: typeof ESlugRoute
  UUrlIdRoute: typeof UUrlIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$urlId': {
      id: '/u/$urlId'
      path: '/u/$urlId'
      fullPath: '/u/$urlId'
      preLoaderRoute: typeof UUrlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/me': {
      id: '/_protected/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ProtectedMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/events/': {
      id: '/_protected/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ProtectedEventsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/wizard': {
      id: '/_protected/profile/wizard'
      path: '/profile/wizard'
      fullPath: '/profile/wizard'
      preLoaderRoute: typeof ProtectedProfileWizardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/edit': {
      id: '/_protected/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProtectedProfileEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/events/new': {
      id: '/_protected/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof ProtectedEventsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/u/$urlId/p/$token': {
      id: '/u/$urlId/p/$token'
      path: '/p/$token'
      fullPath: '/u/$urlId/p/$token'
      preLoaderRoute: typeof UUrlIdPTokenRouteImport
      parentRoute: typeof UUrlIdRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedMeRoute: typeof ProtectedMeRoute
  ProtectedEventsNewRoute: typeof ProtectedEventsNewRoute
  ProtectedProfileEditRoute: typeof ProtectedProfileEditRoute
  ProtectedProfileWizardRoute: typeof ProtectedProfileWizardRoute
  ProtectedEventsIndexRoute: typeof ProtectedEventsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMeRoute: ProtectedMeRoute,
  ProtectedEventsNewRoute: ProtectedEventsNewRoute,
  ProtectedProfileEditRoute: ProtectedProfileEditRoute,
  ProtectedProfileWizardRoute: ProtectedProfileWizardRoute,
  ProtectedEventsIndexRoute: ProtectedEventsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface UUrlIdRouteChildren {
  UUrlIdPTokenRoute: typeof UUrlIdPTokenRoute
}

const UUrlIdRouteChildren: UUrlIdRouteChildren = {
  UUrlIdPTokenRoute: UUrlIdPTokenRoute,
}

const UUrlIdRouteWithChildren =
  UUrlIdRoute._addFileChildren(UUrlIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ESlugRoute: ESlugRoute,
  UUrlIdRoute: UUrlIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
